server:
  port: 8080

spring:
  application:
    name: cim
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:https://localhost:8585/eureka}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      oms:
        failure-rate-threshold: 50
        minimum-number-of-calls: 4
        sliding-window-size: 10
        wait-duration-in-open-state: 15s
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 1
        minimum-number-of-calls-in-half-open-state: 1
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    heapdump:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j: DEBUG
