server:
  port: 0
spring:
  application:
    name: cim
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
    prefer-ip-address: true