server:
  port: 0
spring:
  application:
    name: oms
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
    prefer-ip-address: true
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: OMS Appliction
    description: This is a order management application
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17